"""Company/branch/employee/customer/supplier/product generation for the bulk
demo-data seed. Every company gets exactly what production's real signup
flow gives it (seed_company_defaults()'s control accounts, voucher types,
tax codes) plus a fixed-size roster of branches/employees/master data, so
the transactions generated by ledger.py always have valid accounts and
parties to reference.

Small-N data (companies, branches, admin users — at most ~1,100 rows total
across a 100-company run) uses plain ORM db.add()/flush, matching every
existing seed script in this repo. Larger per-company pools (employees,
customers, suppliers, products) use SQLAlchemy 2.0 Core bulk inserts
(db.execute(insert(Model), [rows])), since add_seed_50_real.py's row-by-row
db.add() pattern does not scale past a few hundred rows per table.
"""
from __future__ import annotations

import json
import random
from dataclasses import dataclass, field
from decimal import Decimal

from faker import Faker
from sqlalchemy import insert
from sqlalchemy.orm import Session

from app.company_defaults import seed_company_defaults
from app.models import AppDataRecord, Account, Branch, Company, Employee, TaxCode, User, uuid
from app.security import hash_password


EMIRATES = ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"]
BUSINESS_SUFFIXES = ["Trading LLC", "General Contracting LLC", "Logistics FZE", "Facility Services LLC", "Building Materials LLC", "Solutions FZE", "Retail Group LLC", "Industries LLC"]
DEPARTMENTS = ["Finance", "Sales", "Operations", "HR", "Procurement", "Warehouse", "IT", "Customer Service"]
DESIGNATIONS = ["Staff", "Senior Executive", "Team Lead", "Manager", "Coordinator", "Officer", "Analyst", "Supervisor"]

# (category, base name, unit, base price) — reused as templates and varied
# per company via a size/spec tag, matching add_seed_50_real.py's existing
# round-number-suffix convention rather than inventing a new naming scheme.
PRODUCT_TEMPLATES = [
    ("Materials", "Steel Rods", "Ton", "4200.00"),
    ("Logistics", "Local Delivery Service", "Trip", "850.00"),
    ("Furniture", "Ergonomic Office Chair", "Pcs", "375.00"),
    ("Safety", "Safety Helmet", "Pcs", "42.00"),
    ("Electrical", "Copper Cable Roll", "Roll", "690.00"),
    ("Packaging", "Corrugated Packing Box", "Box", "18.50"),
    ("Printing", "Printed Flyer Pack", "Pack", "240.00"),
    ("Fuel", "Diesel Supply", "Liter", "3.15"),
    ("IT", "LED Monitor", "Pcs", "520.00"),
    ("Uniforms", "Staff Uniform Set", "Set", "95.00"),
    ("Utilities", "Drinking Water Case", "Case", "14.00"),
    ("Maintenance", "Maintenance Technician Hour", "Hour", "120.00"),
    ("Courier", "Document Courier", "Trip", "35.00"),
    ("Tools", "Cordless Drill Machine", "Pcs", "310.00"),
    ("Rentals", "Warehouse Space Rental", "Month", "6500.00"),
    ("Safety", "High Visibility Safety Vest", "Pcs", "28.00"),
    ("Services", "Deep Cleaning Service", "Hour", "75.00"),
    ("IT", "Business Laptop", "Pcs", "2850.00"),
    ("Electrical", "LED Panel Light", "Pcs", "86.00"),
    ("Tools", "Industrial Hammer", "Pcs", "64.00"),
]
SIZE_TAGS = ["Standard", "Compact", "Heavy Duty", "Premium", "Economy", "Bulk Pack", "Pro Series", "Value Pack"]


def _stable_tag_offset(run_tag: str) -> int:
    return sum(ord(ch) for ch in run_tag) % 9000


@dataclass
class CompanyBundle:
    index: int
    company_id: str
    admin_user_id: str
    branch_ids: list[str]
    accounts: dict[str, str]       # account code -> Account.id
    tax_codes: dict[str, str]      # tax code -> TaxCode.id
    customers: list[str] = field(default_factory=list)
    suppliers: list[str] = field(default_factory=list)
    products: list[tuple[str, str, Decimal]] = field(default_factory=list)  # (sku, name, unit_price)


def run_tag_trn_prefix(run_tag: str) -> str:
    return f"9{_stable_tag_offset(run_tag):04d}"


def company_trn(run_tag: str, index: int) -> str:
    return f"{run_tag_trn_prefix(run_tag)}{index:010d}"


def existing_company_id(db: Session, run_tag: str, index: int) -> str | None:
    return db.query(Company.id).filter(Company.trn == company_trn(run_tag, index)).scalar()


def create_company_bundle(
    db: Session,
    fake: Faker,
    index: int,
    run_tag: str,
    branches_per_company: int,
    employees_per_company: int,
    customers_per_company: int,
    suppliers_per_company: int,
    products_per_company: int,
    admin_password: str,
) -> CompanyBundle:
    company = Company(
        name=f"{fake.company()} {random.choice(BUSINESS_SUFFIXES)} ({run_tag}-{index:03d})",
        trn=company_trn(run_tag, index),
        country="United Arab Emirates",
        currency="AED",
        vat_rate=Decimal("5.00"),
        emirate=random.choice(EMIRATES),
        business_type=random.choice(["LLC", "FZE", "Sole Establishment", "Free Zone Company"]),
        address=f"{fake.building_number()} {fake.street_name()}, {random.choice(EMIRATES)}, UAE",
    )
    db.add(company)
    db.flush()

    seed_company_defaults(db, company.id)
    db.flush()

    accounts = {row.code: row.id for row in db.query(Account).filter(Account.company_id == company.id).all()}
    tax_codes = {row.code: row.id for row in db.query(TaxCode).filter(TaxCode.company_id == company.id).all()}

    admin = User(
        company_id=company.id,
        email=f"admin{index:04d}@{run_tag.lower()}.demo.taxflowapp.com",
        full_name=fake.name(),
        role="admin",
        password_hash=hash_password(admin_password),
    )
    db.add(admin)
    db.flush()

    branch_ids: list[str] = []
    for b in range(1, branches_per_company + 1):
        branch = Branch(
            company_id=company.id,
            name=f"{random.choice(EMIRATES)} Branch {b:02d}",
            code=f"{run_tag}-{index:03d}-BR{b:02d}",
            city=random.choice(EMIRATES),
            status="Active",
        )
        db.add(branch)
        db.flush()
        branch_ids.append(branch.id)

    _bulk_insert_employees(db, fake, company.id, branch_ids, index, run_tag, employees_per_company)
    customers = _bulk_insert_customers(db, fake, company.id, index, run_tag, customers_per_company)
    suppliers = _bulk_insert_suppliers(db, fake, company.id, index, run_tag, suppliers_per_company)
    products = _bulk_insert_products(db, company.id, index, run_tag, products_per_company)

    return CompanyBundle(
        index=index,
        company_id=company.id,
        admin_user_id=admin.id,
        branch_ids=branch_ids,
        accounts=accounts,
        tax_codes=tax_codes,
        customers=customers,
        suppliers=suppliers,
        products=products,
    )


def _bulk_insert_employees(db: Session, fake: Faker, company_id: str, branch_ids: list[str], index: int, run_tag: str, count: int) -> None:
    rows = []
    for n in range(1, count + 1):
        rows.append({
            "id": uuid(),
            "company_id": company_id,
            "employee_no": f"{run_tag}-{index:03d}-EMP-{n:04d}",
            "full_name": fake.name(),
            "department": random.choice(DEPARTMENTS),
            "designation": random.choice(DESIGNATIONS),
            "basic_salary": Decimal(random.randrange(3500, 22000, 250)),
            "status": "active",
            "branch_id": branch_ids[(n - 1) % len(branch_ids)],
        })
    if rows:
        db.execute(insert(Employee), rows)


def _bulk_insert_customers(db: Session, fake: Faker, company_id: str, index: int, run_tag: str, count: int) -> list[str]:
    names: list[str] = []
    rows = []
    for n in range(1, count + 1):
        name = f"{fake.company()} {random.choice(BUSINESS_SUFFIXES)}"
        names.append(name)
        payload = {
            "name": name,
            "trn": f"10044{index:04d}{n:06d}",
            "emirate": random.choice(EMIRATES),
            "email": f"accounts{n:04d}@{run_tag.lower()}{index:03d}.ae",
        }
        rows.append({
            "id": uuid(), "company_id": company_id, "branch_id": None,
            "collection": "customers", "record_key": name, "payload": json.dumps(payload),
        })
    if rows:
        db.execute(insert(AppDataRecord), rows)
    return names


def _bulk_insert_suppliers(db: Session, fake: Faker, company_id: str, index: int, run_tag: str, count: int) -> list[str]:
    names: list[str] = []
    rows = []
    for n in range(1, count + 1):
        name = f"{fake.company()} {random.choice(['Supplies LLC', 'Materials Trading LLC', 'Distribution FZE', 'Wholesale LLC'])}"
        names.append(name)
        payload = {
            "name": name,
            "trn": f"10055{index:04d}{n:06d}",
            "category": random.choice([t[0] for t in PRODUCT_TEMPLATES]),
            "email": f"accounts{n:04d}@supplier{run_tag.lower()}{index:03d}.ae",
        }
        rows.append({
            "id": uuid(), "company_id": company_id, "branch_id": None,
            "collection": "vendors", "record_key": name, "payload": json.dumps(payload),
        })
    if rows:
        db.execute(insert(AppDataRecord), rows)
    return names


def _bulk_insert_products(db: Session, company_id: str, index: int, run_tag: str, count: int) -> list[tuple[str, str, Decimal]]:
    products: list[tuple[str, str, Decimal]] = []
    rows = []
    for n in range(1, count + 1):
        category, base_name, unit, base_price = PRODUCT_TEMPLATES[(n - 1) % len(PRODUCT_TEMPLATES)]
        variant = (n - 1) // len(PRODUCT_TEMPLATES) + 1
        tag = SIZE_TAGS[(variant - 1) % len(SIZE_TAGS)]
        name = f"{base_name} ({tag})" if variant > 1 else base_name
        sku = f"{run_tag}-{index:03d}-SKU{n:05d}"
        price = (Decimal(base_price) * (Decimal("0.9") + Decimal(random.randrange(0, 40)) / Decimal("100"))).quantize(Decimal("0.01"))
        products.append((sku, name, price))
        payload = {"code": sku, "name": name, "category": category, "unit": unit, "price": str(price), "vat": "Standard 5%"}
        rows.append({
            "id": uuid(), "company_id": company_id, "branch_id": None,
            "collection": "products", "record_key": sku, "payload": json.dumps(payload),
        })
    if rows:
        db.execute(insert(AppDataRecord), rows)
    return products
